
name: Austin Lanari
description: Comics & Coding
meta_description: "Foggy's blog, for building blogs, and blogging on blogs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: 'https://foggy1.github.io/blog/'
google_analytics: 'UA-80918633-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://foggy1.github.io'
author:         'Austin Lanari'

