
name: Coding & Comics
# description: Ruby lover. Javascript Apologist.
# meta_description: "Foggy's blog, for building blogs, and blogging on blogs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: 'https://foggy1.github.io/'
google_analytics: 'UA-80918633-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://foggy1.github.io'
author:         'Austin Lanari'

